crosswalk:
  type: "midpoint"
  nodes:
    - [253]
    - [258]
    - [82, 164]
    - [81, 165]
    - [177]
    - [7, 151]
    - [284, 285]
    - [226, 227]

highway_1:
  type: "range"
  nodes:
    - [400, 425]

highway_2:
  type: "range"
  nodes:
    - [422, 403]

intersection:
  type: "midpoint"
  nodes:
    - [60]
    - [85]
    - [96]
    - [21]
    - [9]
    - [105]
    - [33]
    - [45]
    - [78]
    - [210]

parking:
  type: "range"
  nodes:
    - [228, 239]

roundabout:
  type: "midpoint"
  nodes:
    - [340, 335]

buslane:
  type: "range"
  nodes:
    - [271, 289]
